version: "3.8"

services:
  senior_project:
    image: senior_project_img  # Replace with your actual image name
    container_name: senior_project_container
    environment:
      - NVIDIA_VISIBLE_DEVICES=0  # Use all available GPUs
    volumes:
      - .:/app  # Mounts the current directory to /app in the container
    working_dir: /app
    stdin_open: true  # Keeps the container open for interaction
    tty: true         # Enables an interactive terminal
    shm_size: "16gb"  # Adjust shared memory size to prevent out-of-memory issues
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
